import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the test suite, not written by anyone: the Playwright build
    // output and its HTML report. Linting them buries real findings under
    // thousands of problems — but only for someone who has run the suite, which
    // is why it went unnoticed. Both are gitignored for the same reason.
    ".next-test/**",
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
