import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the test suite, not written by anyone: the Playwright build
    // output and its HTML report. Linting them buries real findings under
    // thousands of problems — but only for someone who has run the suite, which
    // is why it went unnoticed. Both are gitignored for the same reason.
    ".next-test/**",
    "playwright-report/**",
    "test-results/**",
  ]),
  // Honour the conventional leading-underscore marker for intentionally unused
  // bindings (interface-shaped stubs like the printer adapters, placeholder
  // callback args, catch bindings). Applies everywhere.
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
  // Test specs destructure the `seed` fixture purely to trigger the DB
  // reset+seed before each test (see tests/fixtures/test-base.ts). It's
  // intentionally often unused, so don't flag it as an unused variable.
  {
    files: ["tests/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^(_|seed$)",
          varsIgnorePattern: "^(_|seed$)",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
]);

export default eslintConfig;
