blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/printtrack/3d-print-ms/discussions
    about: Ask questions or discuss ideas in GitHub Discussions
